import { expect, it } from 'vitest';
import fixture from '../../e2e/fixtures/opaque-board-ids.json';
import { createPuzzleStore } from '../store/puzzleStore';

it('changes only the geometry of an opaque board and retains its original shape through preview, history and native files', () => {
  const store = createPuzzleStore().useStore;
  expect(store.getState().importPuzzle(JSON.stringify(fixture))).toBe(true);
  store.getState().addVertexSurface({ vertexId: 'bottom|R', layer: 'answer', color: '#ff0000' });
  const original = store.getState().topology!, content = store.getState().puzzle;
  store.getState().setTopologyPreset('wave');
  store.getState().setTopologyIntensity(0.5);
  store.getState().setPreviewGrid({ gridType: 'square', rows: 1, cols: 2, cellSize: 60 });
  const preview = store.getState().previewTopology!;
  expect(preview.vertices.has('bottom|R')).toBe(true);
  expect(preview.vertices.get('corner:alpha')!.position).not.toEqual(original.vertices.get('corner:alpha')!.position);
  expect(store.getState().topology).toBe(original);
  store.getState().setGrid({ rows: 1, cols: 2, cellSize: 60 });
  const wave = store.getState().topology!;
  expect(wave.vertices).toEqual(preview.vertices);
  for (const [id, cell] of original.cells) expect(wave.cells.get(id)?.boundaryVertices).toEqual(cell.boundaryVertices);
  for (const [id, edge] of original.edges) expect(wave.edges.get(id)).toMatchObject({ startVertex: edge.startVertex, endVertex: edge.endVertex });
  expect(store.getState().puzzle).toBe(content);
  store.getState().undo();
  expect(store.getState().topology).toBe(original);
  expect(store.getState().topologyPreset).toBe('square');
  store.getState().redo();
  expect(store.getState().topology).toBe(wave);
  expect(store.getState().topologyPreset).toBe('wave');
  store.getState().applyTopologyPreset();
  expect(store.getState().topology!.vertices).toEqual(wave.vertices);
  expect(store.getState().importPuzzle(store.getState().exportPuzzle())).toBe(true);
  store.getState().setTopologyPreset('sphere');
  store.getState().applyTopologyPreset();
  store.getState().setTopologyPreset('square');
  store.getState().applyTopologyPreset();
  expect(store.getState().topology!.vertices).toEqual(original.vertices);
  expect(store.getState().topology!.cells).toEqual(original.cells);
  expect(store.getState().topology!.edges).toEqual(original.edges);
  expect(store.getState().topology!.bounds).toEqual(original.bounds);
  expect(store.getState().puzzle).toEqual(content);
});

it('retains hidden origins when scaling and rejects a partial native deformation snapshot without replacing the live board', () => {
  const store = createPuzzleStore().useStore;
  store.getState().importPuzzle(JSON.stringify(fixture));
  store.getState().setTopologyPreset('wave');
  store.getState().setTopologyIntensity(0.5);
  store.getState().applyTopologyPreset();
  store.getState().toggleCellDisabled('co');
  store.getState().setGrid({ cellSize: 120, outerPadding: 30 });
  const state = store.getState(), saved = store.getState().exportPuzzle();
  const broken = JSON.parse(saved);
  delete broken.topologySettings.topology.vertices[0][1].basePosition;
  expect(store.getState().importPuzzle(JSON.stringify(broken))).toBe(false);
  expect(store.getState().topology).toBe(state.topology);
  expect(store.getState().puzzle).toBe(state.puzzle);
  expect(store.getState().importPuzzle(saved)).toBe(true);
  store.getState().setTopologyPreset('square');
  store.getState().applyTopologyPreset();
  expect(store.getState().topology!.cells.has('co')).toBe(false);
  store.getState().toggleCellDisabled('co');
  expect(store.getState().topology!.vertices.get('bottom|L')!.position).toEqual({ x: 70, y: 190 });
  expect(store.getState().topology!.vertices.get('joint/top')!.position).toEqual({ x: 150, y: 30 });
});
