import { expect, it } from 'vitest';
import fixture from '../../e2e/fixtures/opaque-hex-board.json';
import { createPuzzleStore } from '../store/puzzleStore';
import { resizeTopology } from '../utils/topology/resize';
import { getHexCenter, findNearestHexCell, getHexCellId } from '../utils/hexGridUtils';

it('retains opaque hex vertices and shared edges on growth, and restores trimmed annotations atomically', () => {
  const store = createPuzzleStore().useStore;
  expect(store.getState().importPuzzle(JSON.stringify(fixture))).toBe(true);
  const original = store.getState().topology!, content = store.getState().puzzle;
  const direct = resizeTopology(original, store.getState().grid, { ...store.getState().grid, cols: 3 });
  expect(direct.topology.vertices.get('south-tip')!.position).toEqual(original.vertices.get('south-tip')!.position);
  store.getState().setPreviewGrid({ gridType: 'hex', rows: 2, cols: 3, cellSize: 40 });
  expect(store.getState().previewTopology!.vertices.get('south-tip')!.position).toEqual(original.vertices.get('south-tip')!.position);
  store.getState().resizeGrid({ cols: 3 });
  for (const [id, vertex] of original.vertices) expect(store.getState().topology!.vertices.get(id)?.position).toEqual(vertex.position);
  for (const [id, cell] of original.cells) expect(store.getState().topology!.cells.get(id)?.boundaryVertices).toEqual(cell.boundaryVertices);
  expect(store.getState().puzzle).toEqual(content);
  expect(store.getState().importPuzzle(store.getState().exportPuzzle())).toBe(true);
  store.getState().enterTrial();
  const beforeTrim = store.getState();
  store.getState().setGrid({ rows: 1 });
  expect(store.getState().puzzle.answer.vertexSurfaces?.note).toBeUndefined();
  expect(store.getState().puzzle.problem.numbers.clue).toBeUndefined();
  store.getState().undo();
  expect(store.getState().puzzle).toBe(beforeTrim.puzzle);
  expect(store.getState().trialStack).toBe(beforeTrim.trialStack);
  expect(store.getState().topology).toBe(beforeTrim.topology);
  // Removing the neighbor keeps an edge that still bounds the surviving cell.
  store.getState().setGrid({ cols: 1 });
  const line = content.problem.lines.divider;
  expect(store.getState().puzzle.problem.lines.divider).toEqual(line);
  expect(store.getState().topology!.edges.get(line.edgeId!)?.adjacentCells).toEqual(['room|SW']);
});

it('preserves hex connections and stagger through odd top/left margins, hidden cells, deformation and files', () => {
  const store = createPuzzleStore().useStore;
  store.getState().importPuzzle(JSON.stringify(fixture));
  const original = store.getState().topology!;
  const position = original.vertices.get('south-tip')!.position;
  store.getState().toggleCellDisabled('room|SW');
  store.getState().setTopologyPreset('wave');
  store.getState().applyTopologyPreset();
  store.getState().resizeGrid({ marginTop: 1, marginLeft: 1 });
  expect(store.getState().grid.hexRowOffset).toBe(1);
  const base = store.getState().topology!.exclusionBase!;
  expect(base.cells.get('room|SW')?.boundaryVertices).toEqual(original.cells.get('room|SW')!.boundaryVertices);
  expect(base.cells.get('room|SW')?.index).toEqual([2, 1]);
  expect(base.vertices.get('south-tip')!.basePosition!.x).toBeCloseTo(position.x + 20 * Math.sqrt(3));
  expect(base.vertices.get('south-tip')!.basePosition!.y).toBeCloseTo(position.y + 30);
  const saved = store.getState().exportPuzzle();
  const broken = JSON.parse(saved);
  broken.topologySettings.topology.sourceConfig.hexRowOffset = 0;
  expect(store.getState().importPuzzle(JSON.stringify(broken))).toBe(false);
  const brokenGrid = JSON.parse(saved);
  brokenGrid.grid.hexRowOffset = 0;
  expect(store.getState().importPuzzle(JSON.stringify(brokenGrid))).toBe(false);
  expect(store.getState().importPuzzle(saved)).toBe(true);
  store.getState().toggleCellDisabled('room|SW');
  store.getState().setTopologyPreset('square');
  store.getState().applyTopologyPreset();
  store.getState().resizeGrid({ marginTop: 2 });
  expect(store.getState().grid.hexRowOffset).toBe(0);
  expect(store.getState().topology!.vertices.get('south-tip')!.position.y).toBeCloseTo(position.y + 60);
  store.getState().undo();
  expect(store.getState().grid.hexRowOffset).toBe(1);
  expect(store.getState().topology!.vertices.get('south-tip')!.position.y).toBeCloseTo(position.y + 30);
  store.getState().resizeGrid({ marginTop: 0, marginLeft: 0 });
  const final = store.getState().topology!;
  expect(final.vertices.get('south-tip')!.position.x).toBeCloseTo(position.x);
  expect(final.vertices.get('south-tip')!.position.y).toBeCloseTo(position.y);
  for (const [id, edge] of original.edges) expect(final.edges.get(id)).toMatchObject({ startVertex: edge.startVertex, endVertex: edge.endVertex });
});

it('aligns legacy hex drawing and hit testing with the retained graph after margin insertion and reload', () => {
  const store = createPuzzleStore().useStore;
  store.getState().setUseTopology(false);
  store.getState().newPuzzle({ gridType: 'hex', rows: 2, cols: 2, cellSize: 40 });
  const cellId = getHexCellId(1, 0);
  store.getState().addSurface({ cellId, layer: 'problem', color: '#ff0000' });
  const surfaces = store.getState().puzzle.problem.surfaces;
  store.getState().setGrid({ cols: 3, marginTop: 1, marginLeft: 1 });
  expect(store.getState().importPuzzle(store.getState().exportPuzzle())).toBe(true);
  const state = store.getState();
  expect(state.useTopology).toBe(false);
  const cell = [...state.topology!.cells.values()].find(c => c.index?.[0] === 2 && c.index?.[1] === 1)!;
  const center = getHexCenter(1, 0, state.grid);
  expect(center.x).toBeCloseTo(cell.center.x);
  expect(center.y).toBeCloseTo(cell.center.y);
  expect(findNearestHexCell(center, state.grid)).toEqual({ row: 1, col: 0 });
  expect(state.puzzle.problem.surfaces).toEqual(surfaces);
  store.getState().setCellDisabled(cellId, true);
  expect(store.getState().topology!.cells.has(cell.id)).toBe(false);
  store.getState().undo();
  expect(store.getState().topology!.cells.has(cell.id)).toBe(true);
});
