import { expect, it } from 'vitest';
import { createPuzzleStore } from '../store/puzzleStore';
import { isometricExtentFixture } from '../../e2e/fixtures/isometric-extent';
import { resizeTopology } from '../utils/topology/resize';
import { isometricGridToTopology } from '../utils/topology/special/isometric';

it('keeps hidden face identities and notes through native reload, layout, extent and visibility history', () => {
  const store = createPuzzleStore().useStore;
  expect(store.getState().importPuzzle(JSON.stringify(isometricExtentFixture()))).toBe(true);
  const before = store.getState();
  store.getState().setGrid({ isometricFaces: ['left', 'right'] });
  const hidden = store.getState();
  expect(hidden.topology!.cells.has('cell-0-0')).toBe(false);
  expect(hidden.topology!.exclusionBase!.cells.get('cell-0-0')?.boundaryVertices).toEqual(before.topology!.cells.get('cell-0-0')!.boundaryVertices);
  expect(hidden.puzzle).toEqual(before.puzzle);
  expect(store.getState().importPuzzle(hidden.exportPuzzle())).toBe(true);
  store.getState().setGrid({ cellSize: 60, outerPadding: 30 });
  store.getState().setTopologyPreset('wave'); store.getState().applyTopologyPreset();
  store.getState().setGrid({ cols: 4 });
  expect(store.getState().grid.cols).toBe(4);
  expect(store.getState().topology!.cells.has('cell-0-0')).toBe(false);
  store.getState().setTopologyPreset('square'); store.getState().applyTopologyPreset();
  const resized = store.getState();
  store.getState().setGrid({ isometricFaces: ['right', 'top', 'left'] });
  expect(store.getState().topology!.cells.get('cell-0-0')?.isometricFace).toBe('top');
  expect(store.getState().puzzle).toEqual(before.puzzle);
  expect(store.getState().topology!.vertices.has('corner/roof|β')).toBe(true);
  store.getState().undo();
  expect(store.getState().topology).toBe(resized.topology);
  expect(store.getState().grid).toBe(resized.grid);
  store.getState().redo();
  expect(store.getState().importPuzzle(store.getState().exportPuzzle())).toBe(true);
  expect(store.getState().topology!.cells.has('cell-0-0')).toBe(true);
});

it('keeps the logical horizontal face through interior/exterior changes and retires splitting seam references atomically', () => {
  const store = createPuzzleStore().useStore;
  expect(store.getState().importPuzzle(JSON.stringify(isometricExtentFixture()))).toBe(true);
  const source = store.getState().topology!;
  const seam = [...source.vertices.values()].sort((a, b) => b.position.x - a.position.x || a.position.y - b.position.y)[0];
  store.getState().addVertexSurface({ vertexId: seam.id, color: '#00ff00', layer: 'answer' });
  store.getState().enterTrial();
  const before = store.getState();
  store.getState().setPreviewGrid({ gridType: 'iso', rows: 3, cols: 3, level: 2, isometricView: 'interior' });
  expect(store.getState().previewTopology!.cells.get('cell-0-0')?.isometricFace).toBe('bottom');
  store.getState().setGrid({ isometricView: 'interior' });
  const after = store.getState();
  expect(after.topology!.cells.get('cell-0-0')?.isometricFace).toBe('bottom');
  expect(after.topology!.vertices.has('corner/roof|β')).toBe(true);
  expect(after.topology!.vertices.get('corner/roof|β')!.position).not.toEqual(source.vertices.get('corner/roof|β')!.position);
  expect(after.puzzle.problem.numbers).toEqual(before.puzzle.problem.numbers);
  expect(after.topology!.vertices.has(seam.id)).toBe(false);
  expect(Object.values(after.puzzle.answer.vertexSurfaces!).some(n => n.vertexId === seam.id)).toBe(false);
  expect(Object.values(after.trialStack[0].vertexSurfaces!).some(n => n.vertexId === seam.id)).toBe(false);
  store.getState().undo();
  expect(store.getState().topology).toBe(source);
  expect(store.getState().puzzle).toBe(before.puzzle);
  expect(store.getState().trialStack).toBe(before.trialStack);
  store.getState().redo();
  expect(store.getState().importPuzzle(store.getState().exportPuzzle())).toBe(true);
  store.getState().setGrid({ isometricView: 'exterior' });
  expect(store.getState().topology!.cells.get('cell-0-0')?.isometricFace).toBe('top');
  expect(store.getState().topology!.vertices.get('corner/roof|β')?.position).toEqual(source.vertices.get('corner/roof|β')!.position);
  expect(store.getState().topology!.vertices.has(seam.id)).toBe(false);
});

it('extends a partial face archive once, and rejects ambiguous horizontal-face migrations', () => {
  const grid = { ...isometricExtentFixture().grid, isometricFaces: ['left'] as ['left'] };
  const source = isometricGridToTopology(grid);
  const all = { ...grid, isometricFaces: ['top', 'left', 'right'] as ['top', 'left', 'right'] };
  const grown = resizeTopology(source, grid, all).topology;
  for (const id of source.cells.keys()) expect(grown.cells.has(id)).toBe(true);
  const hidden = resizeTopology(grown, all, grid).topology;
  expect(new Set(hidden.cells.keys())).toEqual(new Set(source.cells.keys()));
  const restored = resizeTopology(hidden, grid, all).topology;
  expect(new Set(restored.cells.keys())).toEqual(new Set(grown.cells.keys()));
  const both = { ...all, isometricFaces: ['top', 'bottom', 'left'] as ['top', 'bottom', 'left'] };
  expect(() => resizeTopology(isometricGridToTopology(both), both, { ...both, isometricView: 'interior' })).toThrow(/isometric/);
});
