import { expect, it } from 'vitest';
import fixture from '../../e2e/fixtures/vertex-surfaces.json';
import concave from '../../e2e/fixtures/merged-extent-board.json';
import legacy from '../../e2e/fixtures/legacy-merged-board.json';
import { createPuzzleStore } from '../store/puzzleStore';
import { resizeTopology } from '../utils/topology/resize';
import { findNearestCellInTopology } from '../utils/topology/queries';

it('splits opaque cells without renumbering boundaries, and restores source cells with independent cuts and history intact', () => {
  const store = createPuzzleStore().useStore;
  store.getState().importPuzzle(JSON.stringify(fixture));
  store.getState().addNumber({ cellId: 'room/a', value: '5', layer: 'problem', color: '#000000', size: 'medium', position: 'center' });
  store.getState().enterTrial();
  const before = store.getState();
  store.getState().addSplitLine('room/a', 'NW!', 'crossing|center');
  const split = store.getState(), op = split.topology!.editOperations![0];
  expect(op.kind).toBe('split');
  if (op.kind !== 'split') throw new Error('Missing cut');
  expect(split.topology!.cells.size).toBe(5);
  expect(split.topology!.cells.has('room/a')).toBe(false);
  for (const [id, vertex] of before.topology!.vertices) expect(split.topology!.vertices.get(id)!.position).toEqual(vertex.position);
  for (const [id, edge] of before.topology!.edges) expect(split.topology!.edges.get(id)).toMatchObject({ startVertex: edge.startVertex, endVertex: edge.endVertex, midpoint: edge.midpoint });
  expect(split.puzzle.problem.numbers).toEqual({});
  expect(split.puzzle.problem.vertexSurfaces).toEqual(before.puzzle.problem.vertexSurfaces);
  store.getState().undo();
  expect(store.getState().puzzle).toBe(before.puzzle);
  expect(store.getState().trialStack).toBe(before.trialStack);
  store.getState().redo();
  store.getState().addNumber({ cellId: op.cellIds[0], value: '17', layer: 'answer', color: '#000000', size: 'medium', position: 'center' });
  store.getState().addLine({ from: op.startVertex, to: op.endVertex, edgeId: op.edgeId, lineTarget: 'edge', layer: 'answer', color: '#0000ff', style: 'solid', thickness: 'thick' });
  store.getState().addSplitLine('room/d', 'crossing|center', 'SE?');
  const independent = store.getState().topology!.editOperations![1];
  const saved = store.getState().exportPuzzle();
  expect(store.getState().importPuzzle(saved)).toBe(true);
  store.getState().removeSplitLine(op.cellIds[0]);
  expect(store.getState().topology!.cells.has('room/a')).toBe(true);
  expect(store.getState().topology!.editOperations).toEqual([independent]);
  expect(store.getState().puzzle.answer.numbers).toEqual({});
  expect(store.getState().puzzle.answer.lines).toEqual({});
  store.getState().undo();
  expect(Object.values(store.getState().puzzle.answer.numbers).map(n => n.value)).toEqual(['17']);
  store.getState().clearSplitLines();
  expect(new Set(store.getState().topology!.cells.keys())).toEqual(new Set(before.topology!.cells.keys()));
  expect(store.getState().topology!.vertices).toEqual(before.topology!.vertices);
  expect(store.getState().importPuzzle(store.getState().exportPuzzle())).toBe(true);
});

it('keeps alternating merge/split operations in one source and retains IDs through layout, exclusion, presets and native reload', () => {
  const store = createPuzzleStore().useStore;
  store.getState().importPuzzle(JSON.stringify(fixture));
  store.getState().mergeCells(['room/a', 'room/b']);
  const firstMerge = store.getState().topology!.mergeGroups![0].id;
  store.getState().addSplitLine(firstMerge, 'NW!', 'east/middle');
  const cut = store.getState().topology!.editOperations![1];
  if (cut.kind !== 'split') throw new Error('Missing cut');
  store.getState().mergeCells(cut.cellIds);
  const merged = store.getState().topology!.editOperations!.at(-1)!;
  if (merged.kind !== 'merge') throw new Error('Missing merge');
  store.getState().addSplitLine(merged.id, 'NW!', 'east/middle');
  const second = store.getState().topology!.editOperations!.at(-1)!;
  if (second.kind !== 'split') throw new Error('Missing second cut');
  expect(second.edgeId).not.toBe(cut.edgeId);
  expect(store.getState().topology!.editOperations).toHaveLength(4);
  expect(store.getState().topology!.editBase!.editBase).toBeUndefined();
  expect(store.getState().topology!.editBase!.mergeBase).toBeUndefined();
  store.getState().toggleCellDisabled(second.cellIds[0]);
  store.getState().setTopologyPreset('wave'); store.getState().applyTopologyPreset();
  store.getState().setGrid({ cellSize: 80, outerPadding: 30 });
  expect(store.getState().importPuzzle(store.getState().exportPuzzle())).toBe(true);
  store.getState().toggleCellDisabled(second.cellIds[0]);
  store.getState().setTopologyPreset('square'); store.getState().applyTopologyPreset();
  const graph = store.getState().topology!;
  expect(graph.vertices.get('NW!')!.position).toEqual({ x: 30, y: 30 });
  expect(graph.vertices.get('crossing|center')!.position).toEqual({ x: 110, y: 110 });
  for (const id of second.cellIds) expect(findNearestCellInTopology(graph, graph.cells.get(id)!.center)?.id).toBe(id);
  store.getState().clearSplitLines();
  expect(store.getState().topology!.cells.has(firstMerge)).toBe(true);
  expect(store.getState().topology!.editOperations).toHaveLength(1);
  store.getState().unmergeCells([firstMerge]);
  expect(new Set(store.getState().topology!.cells.keys())).toEqual(new Set(['room/a', 'room/b', 'room/c', 'room/d']));
});

it('rejects exterior chords and corrupt native operation references without changing the current board', () => {
  const store = createPuzzleStore().useStore;
  store.getState().importPuzzle(JSON.stringify(concave));
  const original = store.getState(), group = original.topology!.mergeGroups![0];
  const vertices = [...original.topology!.vertices.values()];
  const nw = vertices.find(v => v.position.x === 20 && v.position.y === 20)!.id;
  const ne = vertices.find(v => v.position.x === 200 && v.position.y === 20)!.id;
  store.getState().addSplitLine(group.id, nw, ne);
  expect(store.getState().topology).toBe(original.topology);
  store.getState().importPuzzle(JSON.stringify(fixture));
  store.getState().addSplitLine('room/a', 'NW!', 'crossing|center');
  const saved = store.getState().exportPuzzle(), current = store.getState();
  const badId = JSON.parse(saved); badId.topologySettings.topology.editOperations[0].cellIds[0] = 'room/c';
  expect(store.getState().importPuzzle(JSON.stringify(badId))).toBe(false);
  const badOrigin = JSON.parse(saved);
  badOrigin.topologySettings.topology.cells.find(([, cell]: [string, { originalCells?: string[] }]) => cell.originalCells)?.[1].originalCells.splice(0, 1, 'room/c');
  expect(store.getState().importPuzzle(JSON.stringify(badOrigin))).toBe(false);
  const badSource = JSON.parse(saved); badSource.topologySettings.topology.editBase.vertices[0][1].position.x += 1;
  expect(store.getState().importPuzzle(JSON.stringify(badSource))).toBe(false);
  expect(store.getState().topology).toBe(current.topology);
  expect(store.getState().puzzle).toBe(current.puzzle);
});


it('resizes regular split sources while preserving children, and refuses a crop that would invent a cut endpoint', () => {
  for (const gridType of ['square', 'hex'] as const) {
    const store = createPuzzleStore().useStore;
    store.getState().newPuzzle({ gridType, rows: 2, cols: 2, cellSize: 40 });
    const source = [...store.getState().topology!.cells.values()][0];
    store.getState().addSplitLine(source.id, source.boundaryVertices[0], source.boundaryVertices[gridType === 'hex' ? 3 : 2]);
    const operation = store.getState().topology!.editOperations![0];
    if (operation.kind !== 'split') throw new Error('Missing split');
    store.getState().addNumber({ cellId: operation.cellIds[0], value: '17', layer: 'problem', color: '#000000', size: 'medium', position: 'center' });
    const content = store.getState().puzzle;
    store.getState().setGrid({ cols: 3 });
    expect(store.getState().topology!.editOperations).toEqual([operation]);
    expect(store.getState().puzzle).toEqual(content);
    store.getState().toggleCellDisabled(operation.cellIds[0]);
    store.getState().setTopologyPreset('wave'); store.getState().applyTopologyPreset();
    store.getState().resizeGrid({ marginTop: 1, marginLeft: 1, cellSize: 60 });
    expect(store.getState().topology!.cells.has(operation.cellIds[0])).toBe(false);
    expect(store.getState().importPuzzle(store.getState().exportPuzzle())).toBe(true);
    store.getState().toggleCellDisabled(operation.cellIds[0]);
    store.getState().setTopologyPreset('square'); store.getState().applyTopologyPreset();
    store.getState().setGrid({ rows: 1, cols: 1, marginTop: 0, marginLeft: 0, cellSize: 40 });
    expect(store.getState().topology!.cells.size).toBe(2);
    expect(store.getState().topology!.editOperations).toEqual([operation]);
    expect(store.getState().puzzle).toEqual(content);
    expect(store.getState().importPuzzle(store.getState().exportPuzzle())).toBe(true);
  }
  const store = createPuzzleStore().useStore;
  store.getState().newPuzzle({ rows: 2, cols: 2, cellSize: 40 });
  store.getState().mergeCells([...store.getState().topology!.cells.keys()]);
  const merged = store.getState().topology!, id = merged.mergeGroups![0].id;
  const vertices = [...merged.vertices.values()];
  const first = vertices.find(v => v.position.x === 20 && v.position.y === 20)!.id;
  const last = vertices.find(v => v.position.x === 100 && v.position.y === 100)!.id;
  store.getState().addSplitLine(id, first, last);
  const before = store.getState();
  store.getState().setGrid({ rows: 1 });
  expect(store.getState().topology).toBe(before.topology);
  expect(store.getState().grid).toBe(before.grid);
  expect(() => resizeTopology(before.topology!, before.grid, { ...before.grid, rows: 1 })).toThrow('Cannot resize');
  store.getState().setPreviewGrid({ gridType: 'square', rows: 1, cols: 2, cellSize: 40 });
  expect(store.getState().previewTopology).toBeNull();
});


it('splits one legacy merged cell while preserving another legacy boundary and its surviving long edges', () => {
  const store = createPuzzleStore().useStore;
  store.getState().importPuzzle(JSON.stringify(legacy));
  const before = store.getState(), full = before.topology!, groups = full.mergeGroups!;
  const target = full.cells.get(groups[1].id)!;
  store.getState().addSplitLine(target.id, target.boundaryVertices[0], target.boundaryVertices[2]);
  const split = store.getState().topology!;
  expect(split.cells.size).toBe(full.cells.size + 1);
  expect(split.cells.get(groups[0].id)).toMatchObject({ center: full.cells.get(groups[0].id)!.center, boundaryVertices: full.cells.get(groups[0].id)!.boundaryVertices });
  for (const [id, edge] of full.edges) expect(split.edges.get(id)).toMatchObject({ startVertex: edge.startVertex, endVertex: edge.endVertex, midpoint: edge.midpoint });
  expect(store.getState().puzzle.problem.lines).toEqual(before.puzzle.problem.lines);
  expect(store.getState().puzzle.answer.vertexSurfaces).toEqual(before.puzzle.answer.vertexSurfaces);
  expect(store.getState().importPuzzle(store.getState().exportPuzzle())).toBe(true);
  store.getState().clearSplitLines();
  expect(new Set(store.getState().topology!.cells.keys())).toEqual(new Set(full.cells.keys()));
});
