/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmengineresult_free: (a: number, b: number) => void;
export const wasmengineresult_difficulty: (a: number) => number;
export const wasmengineresult_answer_kind: (a: number) => number;
export const wasmengineresult_diagonal: (a: number) => number;
export const wasmengineresult_default_block: (a: number) => number;
export const wasmengineresult_pattern: (a: number) => [number, number];
export const wasmengineresult_problem: (a: number) => [number, number];
export const wasmengineresult_solution: (a: number) => [number, number];
export const wasmengineresult_block_labels: (a: number) => [number, number];
export const solve_puzzle: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: bigint, k: number, l: number) => [number, number, number];
export const generate_puzzle: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: bigint, m: number, n: number, o: number, p: number, q: number) => [number, number, number];
export const generate_random_puzzle: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: bigint, j: number, k: number, l: number, m: number, n: number) => [number, number, number];
export const benchmark: (a: number, b: bigint) => [number, number, number];
export const __wbg_wasmxmlpuzzle_free: (a: number, b: number) => void;
export const wasmxmlpuzzle_size: (a: number) => number;
export const wasmxmlpuzzle_difficulty: (a: number) => number;
export const wasmxmlpuzzle_diagonal: (a: number) => number;
export const wasmxmlpuzzle_default_block: (a: number) => number;
export const wasmxmlpuzzle_pattern: (a: number) => [number, number];
export const wasmxmlpuzzle_hidden: (a: number) => [number, number];
export const wasmxmlpuzzle_problem: (a: number) => [number, number];
export const wasmxmlpuzzle_solution: (a: number) => [number, number];
export const wasmxmlpuzzle_block_labels: (a: number) => [number, number];
export const parse_npgen_xml: (a: number, b: number) => [number, number, number];
export const format_npgen_xml: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number) => [number, number, number, number];
export const all_techniques_mask: () => number;
export const all_uniqueness_mask: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
