import { test, expect } from './fixtures';
import { isometricExtentFixture } from './fixtures/isometric-extent';
import { openPuzzleFile, savePuzzleFile } from './puzzle-file';
import { point } from './canvas-point';

test('isometric growth retains vertex notes, accepts new-cell input and restores trimmed content @production', async ({ page, isMobile }, info) => {
  const fixture = isometricExtentFixture();
  await page.goto('/master'); await openPuzzleFile(page, Buffer.from(JSON.stringify(fixture)));
  const note = page.locator('.vertex-surface-layer-answer [data-vertex-surface="corner/roof|β"]');
  const originalPath = await note.getAttribute('d');
  await page.screenshot({ path: info.outputPath('isometric-original.png') });
  const close = page.getByTitle('Close', { exact: true });
  const resize = async (label: string, value: string, apply = true) => {
    if (await close.isVisible()) await close.click();
    await page.getByRole('button', { name: 'Problem', exact: true }).click();
    await page.getByRole('button', { name: 'Grid', exact: true }).click();
    await page.getByRole('button', { name: 'Type', exact: true }).click();
    await page.getByRole('button', { name: 'Preset', exact: true }).click();
    const opener = page.getByTitle('Properties', { exact: true });
    if (await opener.isVisible()) await opener.click();
    await page.getByText(label, { exact: true }).locator('..').getByRole('spinbutton').fill(value);
    if (!apply) return;
    await page.getByRole('button', { name: 'Apply', exact: true }).click();
    if (await close.isVisible()) await close.click();
  };
  await resize('Columns', '4');
  await page.screenshot({ path: info.outputPath('isometric-expanded.png') });
  await expect(note).toHaveAttribute('d', originalPath!);
  const expanded = await savePuzzleFile(page);
  expect(expanded.state).toEqual(fixture.state);
  const vertices = new Map(expanded.topologySettings!.topology!.vertices);
  expect(vertices.get('corner/roof|β')?.position).toEqual(new Map(fixture.topologySettings!.topology!.vertices).get('corner/roof|β')!.position);
  await page.getByTitle(/Undo \(Ctrl\+Z\)/).first().click();
  expect((await savePuzzleFile(page)).grid.cols).toBe(3);
  await page.getByTitle(/Redo/).first().click();
  await openPuzzleFile(page, Buffer.from(JSON.stringify(expanded)));
  await resize('Level', '3');
  const taller = await savePuzzleFile(page);
  expect(taller.grid.level).toBe(3);
  expect(taller.state).toEqual(expanded.state);
  for (const [id] of expanded.topologySettings!.topology!.cells) expect(taller.topologySettings!.topology!.cells.some(([current]) => current === id)).toBe(true);
  await expect(note).toHaveAttribute('d', originalPath!);
  await page.screenshot({ path: info.outputPath('isometric-taller.png') });
  await page.getByTitle(/Undo \(Ctrl\+Z\)/).first().click();
  await page.getByRole('button', { name: 'Answer', exact: true }).click();
  await page.getByRole('button', { name: 'Surface', exact: true }).click();
  const cell = expanded.topologySettings!.topology!.cells.map(([, c]) => c).filter(c => c.index?.[0] === 2 && c.index?.[1] === 3).sort((a, b) => a.center.y - b.center.y)[0];
  const p = await point(page, cell.center.x, cell.center.y);
  if (isMobile) await page.touchscreen.tap(p.x, p.y); else await page.mouse.click(p.x, p.y);
  expect(Object.values((await savePuzzleFile(page)).state.answer.surfaces).map(s => s.cellId)).toEqual([cell.id]);
  await resize('Rows', '1');
  await expect(note).toHaveCount(0);
  const trimmed = await savePuzzleFile(page);
  expect(trimmed.state.answer.vertexSurfaces).toEqual({});
  expect(trimmed.state.answer.surfaces).toEqual({});
  expect(trimmed.state.problem.numbers).toEqual({});
  await page.getByTitle(/Undo \(Ctrl\+Z\)/).first().click();
  await expect(note).toHaveAttribute('d', originalPath!);
  await openPuzzleFile(page, Buffer.from(JSON.stringify(await savePuzzleFile(page))));
  await expect(note).toHaveAttribute('d', originalPath!);
  await expect(page.locator('.number-layer-problem')).toContainText('17');
  await page.screenshot({ path: info.outputPath('isometric-restored.png') });
  // Unknown native geometry must not turn into a regular regenerated board.
  const custom = structuredClone(expanded);
  const customCell = custom.topologySettings!.topology!.cells.find(([id]) => id === 'cell-0-0')![1];
  customCell.center.x += 3;
  await openPuzzleFile(page, Buffer.from(JSON.stringify(custom)));
  await resize('Columns', '5', false);
  await expect(page.getByRole('button', { name: 'Apply', exact: true })).toBeDisabled();
  await expect(page.getByRole('status')).toContainText('This board cannot be resized');
  await page.screenshot({ path: info.outputPath('isometric-unsupported.png') });
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  const unchanged = await savePuzzleFile(page);
  expect(unchanged.grid).toEqual(custom.grid);
  expect(unchanged.topologySettings!.topology).toEqual(custom.topologySettings!.topology);
});
