import { test, expect } from './fixtures';
import { legacyTriangleFixture } from './fixtures/legacy-triangle';
import { openPuzzleFile, savePuzzleFile } from './puzzle-file';
import { point } from './canvas-point';

test('legacy Grid triangles accept right-side vertex input and keep references through resize and files @production', async ({ page, isMobile }, info) => {
  const data = legacyTriangleFixture();
  await page.goto('/master'); await openPuzzleFile(page, Buffer.from(JSON.stringify(data)));
  await page.getByRole('button', { name: 'Answer', exact: true }).click();
  await page.getByRole('button', { name: 'Surface', exact: true }).click();
  const properties = page.getByTitle('Properties', { exact: true }), close = page.getByTitle('Close', { exact: true });
  if (await properties.isVisible()) await properties.click();
  await page.getByRole('group', { name: 'Shading target', exact: true }).getByRole('button', { name: 'Vertex', exact: true }).click();
  if (await close.isVisible()) await close.click();
  await page.screenshot({ path: info.outputPath('legacy-triangle-opened.png') });
  const p = await point(page, 230, 20 + 60 * Math.sqrt(3));
  if (isMobile) await page.touchscreen.tap(p.x, p.y); else await page.mouse.click(p.x, p.y);
  await page.screenshot({ path: info.outputPath('legacy-triangle-painted.png') });
  await expect(page.locator('.vertex-surface-layer-answer [data-vertex-surface]')).toHaveCount(2);
  const painted = await savePuzzleFile(page);
  const original = data.state.answer.vertexSurfaces!.note;
  expect(painted.state.answer.vertexSurfaces!.note).toEqual(original);
  const newNote = Object.values(painted.state.answer.vertexSurfaces!).find(n => n.id !== 'note')!;
  expect(new Map(painted.topologySettings!.topology!.vertices).get(newNote.vertexId)?.position).toEqual({ x: 230, y: expect.closeTo(20 + 60 * Math.sqrt(3)) });
  expect(painted.state.problem.numbers).toEqual(data.state.problem.numbers);
  await page.getByRole('button', { name: 'Problem', exact: true }).click();
  await page.getByRole('button', { name: 'Grid', exact: true }).click();
  await page.getByRole('button', { name: 'Type', exact: true }).click();
  await page.getByRole('button', { name: 'Preset', exact: true }).click();
  if (await properties.isVisible()) await properties.click();
  await page.getByText('Columns', { exact: true }).locator('..').getByRole('spinbutton').fill('5');
  await page.getByRole('button', { name: 'Apply', exact: true }).click();
  if (await close.isVisible()) await close.click();
  const grown = await savePuzzleFile(page);
  expect(grown.state).toEqual(painted.state);
  for (const [id, v] of painted.topologySettings!.topology!.vertices) expect(new Map(grown.topologySettings!.topology!.vertices).get(id)?.position).toEqual(v.position);
  await page.getByTitle(/Undo \(Ctrl\+Z\)/).first().click();
  expect((await savePuzzleFile(page)).grid.cols).toBe(4);
  await page.getByTitle(/Redo/).first().click();
  await openPuzzleFile(page, Buffer.from(JSON.stringify(grown)));
  expect((await savePuzzleFile(page)).state).toEqual(painted.state);
  await expect(page.locator('.vertex-surface-layer-answer [data-vertex-surface]')).toHaveCount(2);
  await expect(page.locator('.number-layer-problem')).toContainText('17');
  await page.screenshot({ path: info.outputPath('legacy-triangle-reloaded.png') });
});
