import { test, expect } from './fixtures';
import { triangleExtentFixture } from './fixtures/triangle-extent';
import { openPuzzleFile, savePuzzleFile } from './puzzle-file';
import { point } from './canvas-point';

test('triangular growth retains vertex notes, accepts new-cell input and restores trimmed content @production', async ({ page, isMobile }, info) => {
  const fixture = triangleExtentFixture();
  await page.goto('/master'); await openPuzzleFile(page, Buffer.from(JSON.stringify(fixture)));
  const note = page.locator('.vertex-surface-layer-answer [data-vertex-surface="corner/bottom|β"]');
  const originalPath = await note.getAttribute('d');
  await page.screenshot({ path: info.outputPath('triangle-original.png') });
  const close = page.getByTitle('Close', { exact: true });
  const resize = async (label: string, value: string) => {
    if (await close.isVisible()) await close.click();
    await page.getByRole('button', { name: 'Problem', exact: true }).click();
    await page.getByRole('button', { name: 'Grid', exact: true }).click();
    await page.getByRole('button', { name: 'Type', exact: true }).click();
    await page.getByRole('button', { name: 'Preset', exact: true }).click();
    const opener = page.getByTitle('Properties', { exact: true });
    if (await opener.isVisible()) await opener.click();
    await page.getByText(label, { exact: true }).locator('..').getByRole('spinbutton').fill(value);
    await page.getByRole('button', { name: 'Apply', exact: true }).click();
    if (await close.isVisible()) await close.click();
  };
  await resize('Columns', '5');
  await page.screenshot({ path: info.outputPath('triangle-expanded.png') });
  await expect(note).toHaveAttribute('d', originalPath!);
  const expanded = await savePuzzleFile(page);
  expect(expanded.state).toEqual(fixture.state);
  const vertices = new Map(expanded.topologySettings!.topology!.vertices);
  for (const [id, v] of fixture.topologySettings!.topology!.vertices) expect(vertices.get(id)?.position).toEqual(v.position);
  await page.getByTitle(/Undo \(Ctrl\+Z\)/).first().click();
  expect((await savePuzzleFile(page)).grid.cols).toBe(4);
  await page.getByTitle(/Redo/).first().click();
  await openPuzzleFile(page, Buffer.from(JSON.stringify(expanded)));
  await page.getByRole('button', { name: 'Answer', exact: true }).click();
  await page.getByRole('button', { name: 'Surface', exact: true }).click();
  const cell = expanded.topologySettings!.topology!.cells.find(([, c]) => c.index?.[0] === 2 && c.index?.[1] === 4)![1];
  const p = await point(page, cell.center.x, cell.center.y);
  if (isMobile) await page.touchscreen.tap(p.x, p.y); else await page.mouse.click(p.x, p.y);
  expect(Object.values((await savePuzzleFile(page)).state.answer.surfaces).map(s => s.cellId)).toEqual([cell.id]);
  await resize('Rows', '2');
  await expect(note).toHaveCount(0);
  const trimmed = await savePuzzleFile(page);
  expect(trimmed.state.answer.vertexSurfaces).toEqual({});
  expect(trimmed.state.answer.surfaces).toEqual({});
  expect(trimmed.state.problem.numbers).toEqual({});
  await page.getByTitle(/Undo \(Ctrl\+Z\)/).first().click();
  await expect(note).toHaveAttribute('d', originalPath!);
  await openPuzzleFile(page, Buffer.from(JSON.stringify(await savePuzzleFile(page))));
  await expect(note).toHaveAttribute('d', originalPath!);
  await expect(page.locator('.number-layer-problem')).toContainText('17');
  await page.screenshot({ path: info.outputPath('triangle-restored.png') });
});
